import {
  Activity,
  AlertOctagon,
  AlertTriangle,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Database,
  FolderCheck,
  GitPullRequest,
  History,
  LayoutDashboard,
  Library,
  LineChart,
  type LucideIcon,
  Scale,
  ScrollText,
  Server,
  Settings,
  ShieldCheck,
  ShieldOff,
  Store,
  UserCheck,
  Users,
  Wrench,
  Zap,
} from 'lucide-react';

import type { NavigationIconName } from '@/lib/navigation';

export const NAVIGATION_ICONS: Record<NavigationIconName, LucideIcon> = {
  LayoutDashboard,
  GitPullRequest,
  CalendarDays,
  History,
  Library,
  ScrollText,
  FolderCheck,
  ClipboardCheck,
  ShieldOff,
  Wrench,
  AlertTriangle,
  AlertOctagon,
  Activity,
  Zap,
  ShieldCheck,
  Scale,
  Building2,
  ClipboardList,
  Server,
  Database,
  UserCheck,
  Users,
  LineChart,
  BarChart3,
  BookOpen,
  Store,
  Bell,
  Settings,
};
