package pdf

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// PDFGenerator defines the interface for generating PDF reports.
type PDFGenerator interface {
	// GenerateComplianceReport produces a PDF compliance report from the given data.
	GenerateComplianceReport(data interface{}) ([]byte, error)

	// GenerateRiskReport produces a PDF risk assessment report from the given data.
	GenerateRiskReport(data interface{}) ([]byte, error)

	// GenerateAuditReport produces a PDF audit report from the given data.
	GenerateAuditReport(data interface{}) ([]byte, error)
}

// ReportPDFGenerator produces auditor-grade PDF reports with cover pages,
// executive summaries, data tables, traffic-light indicators, and watermarks.
type ReportPDFGenerator struct {
	companyName    string
	logoPath       string
	classification string
}

// NewReportPDFGenerator creates a new ReportPDFGenerator.
// companyName is printed on the cover page, logoPath is an optional path to a
// company logo image, and classification (e.g. "CONFIDENTIAL") is stamped on
// every page header/footer.
func NewReportPDFGenerator(companyName, logoPath, classification string) *ReportPDFGenerator {
	return &ReportPDFGenerator{
		companyName:    companyName,
		logoPath:       logoPath,
		classification: classification,
	}
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// newDoc initialises an A4 PDF with headers and footers.
func (g *ReportPDFGenerator) newDoc(title string) *fpdf.Fpdf {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(title, true)
	pdf.SetAuthor("ComplianceForge", true)
	pdf.SetCreator("ComplianceForge GRC Platform", true)
	pdf.SetAutoPageBreak(true, 25)

	// Header on every page: report title (left) + page number (right).
	pdf.SetHeaderFuncMode(func() {
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(128, 128, 128)
		pdf.CellFormat(0, 5, title, "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5, fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "R", false, 0, "")
		pdf.Ln(8)
	}, true)

	// Footer on every page: classification | generation date | branding.
	pdf.SetFooterFunc(func() {
		pdf.SetY(-20)
		pdf.SetFont("Helvetica", "I", 7)
		pdf.SetTextColor(128, 128, 128)
		classText := ""
		if g.classification != "" {
			classText = strings.ToUpper(g.classification) + " | "
		}
		pdf.CellFormat(0, 5,
			fmt.Sprintf("%sGenerated: %s | Generated by ComplianceForge",
				classText, time.Now().UTC().Format("02 Jan 2006 15:04 UTC")),
			"", 0, "C", false, 0, "")
	})

	return pdf
}

// addCoverPage renders a title page with classification stamp, report title,
// subtitle, organisation name, and generation date.
func (g *ReportPDFGenerator) addCoverPage(pdf *fpdf.Fpdf, title, subtitle string) {
	pdf.AddPage()
	pdf.SetFont("Helvetica", "", 12)

	// Top classification stamp
	if g.classification != "" {
		pdf.SetFont("Helvetica", "B", 14)
		pdf.SetTextColor(220, 38, 38) // red
		pdf.CellFormat(0, 15, strings.ToUpper(g.classification), "", 1, "C", false, 0, "")
	}

	pdf.Ln(50)

	// Title
	pdf.SetFont("Helvetica", "B", 28)
	pdf.SetTextColor(30, 58, 138) // indigo-900
	pdf.MultiCell(0, 12, title, "", "C", false)
	pdf.Ln(8)

	// Subtitle
	if subtitle != "" {
		pdf.SetFont("Helvetica", "", 14)
		pdf.SetTextColor(100, 100, 100)
		pdf.MultiCell(0, 8, subtitle, "", "C", false)
	}

	pdf.Ln(20)

	// Organisation name
	pdf.SetFont("Helvetica", "", 16)
	pdf.SetTextColor(50, 50, 50)
	pdf.CellFormat(0, 10, g.companyName, "", 1, "C", false, 0, "")

	// Date
	pdf.Ln(10)
	pdf.SetFont("Helvetica", "", 12)
	pdf.SetTextColor(100, 100, 100)
	pdf.CellFormat(0, 8, time.Now().UTC().Format("02 January 2006"), "", 1, "C", false, 0, "")
}

// addTableOfContents renders a simple table of contents page.
func (g *ReportPDFGenerator) addTableOfContents(pdf *fpdf.Fpdf, sections []string) {
	pdf.AddPage()
	g.addSectionTitle(pdf, "Table of Contents")

	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(50, 50, 50)
	for i, s := range sections {
		pdf.CellFormat(0, 8, fmt.Sprintf("%d.  %s", i+1, s), "", 1, "L", false, 0, "")
	}
	pdf.Ln(4)
}

// addSectionTitle renders a numbered section heading with an underline.
func (g *ReportPDFGenerator) addSectionTitle(pdf *fpdf.Fpdf, title string) {
	pdf.Ln(8)
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetTextColor(30, 58, 138)
	pdf.CellFormat(0, 10, title, "", 1, "L", false, 0, "")
	// Underline
	pdf.SetDrawColor(30, 58, 138)
	pdf.SetLineWidth(0.5)
	y := pdf.GetY()
	pdf.Line(10, y, 200, y)
	pdf.Ln(6)
}

// addSubsectionTitle renders a subsection heading.
func (g *ReportPDFGenerator) addSubsectionTitle(pdf *fpdf.Fpdf, title string) {
	pdf.Ln(4)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(50, 50, 50)
	pdf.CellFormat(0, 8, title, "", 1, "L", false, 0, "")
	pdf.Ln(2)
}

// addParagraph renders body text.
func (g *ReportPDFGenerator) addParagraph(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(50, 50, 50)
	pdf.MultiCell(0, 5, text, "", "L", false)
	pdf.Ln(3)
}

// addKPIRow renders a row of key-performance-indicator cards.
func (g *ReportPDFGenerator) addKPIRow(pdf *fpdf.Fpdf, kpis []struct{ Label, Value, Color string }) {
	if len(kpis) == 0 {
		return
	}
	colWidth := 190.0 / float64(len(kpis))

	for _, kpi := range kpis {
		x := pdf.GetX()
		y := pdf.GetY()

		// Background box
		pdf.SetFillColor(245, 247, 250)
		pdf.RoundedRect(x, y, colWidth-3, 25, 2, "1234", "F")

		// Value
		pdf.SetFont("Helvetica", "B", 18)
		switch kpi.Color {
		case "green":
			pdf.SetTextColor(34, 197, 94)
		case "amber":
			pdf.SetTextColor(234, 179, 8)
		case "red":
			pdf.SetTextColor(239, 68, 68)
		default:
			pdf.SetTextColor(30, 58, 138)
		}
		pdf.SetXY(x+3, y+3)
		pdf.CellFormat(colWidth-6, 8, kpi.Value, "", 0, "C", false, 0, "")

		// Label
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(100, 100, 100)
		pdf.SetXY(x+3, y+14)
		pdf.CellFormat(colWidth-6, 5, kpi.Label, "", 0, "C", false, 0, "")

		pdf.SetXY(x+colWidth, y)
	}
	pdf.Ln(30)
}

// addTable renders a data table with a coloured header row and alternating
// row colours. Long tables are automatically paginated by fpdf's auto-break.
func (g *ReportPDFGenerator) addTable(pdf *fpdf.Fpdf, headers []string, widths []float64, rows [][]string) {
	// Header row
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(30, 58, 138)
	pdf.SetTextColor(255, 255, 255)
	for i, h := range headers {
		pdf.CellFormat(widths[i], 7, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	// Data rows
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(50, 50, 50)
	for idx, row := range rows {
		// Alternating row colours
		if idx%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		for i, cell := range row {
			w := widths[0]
			if i < len(widths) {
				w = widths[i]
			}
			pdf.CellFormat(w, 6, cell, "1", 0, "L", true, 0, "")
		}
		pdf.Ln(-1)
	}
	pdf.Ln(4)
}

// addTrafficLight draws a filled circle at (x, y) coloured red, amber, or
// green to indicate risk/compliance status.
func (g *ReportPDFGenerator) addTrafficLight(pdf *fpdf.Fpdf, x, y float64, color string) {
	switch color {
	case "green":
		pdf.SetFillColor(34, 197, 94)
	case "amber":
		pdf.SetFillColor(234, 179, 8)
	case "red":
		pdf.SetFillColor(239, 68, 68)
	default:
		pdf.SetFillColor(200, 200, 200)
	}
	pdf.Circle(x, y, 3, "F")
}

// addWatermark renders a large, rotated, semi-transparent text across the
// current page (e.g. "DRAFT" or "CONFIDENTIAL").
func (g *ReportPDFGenerator) addWatermark(pdf *fpdf.Fpdf, text string) {
	pdf.SetFont("Helvetica", "B", 60)
	pdf.SetTextColor(230, 230, 230)
	pdf.TransformBegin()
	pdf.TransformRotate(45, 105, 148)
	pdf.Text(35, 190, text)
	pdf.TransformEnd()
}

// render writes the PDF document to a byte slice.
func (g *ReportPDFGenerator) render(pdf *fpdf.Fpdf) ([]byte, error) {
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("rendering PDF: %w", err)
	}
	return buf.Bytes(), nil
}

// ---------------------------------------------------------------------------
// Public report generators
// ---------------------------------------------------------------------------

// GenerateComplianceReport builds a full compliance status PDF.
//
// Expected data keys (map[string]interface{}):
//   - overall_score        float64
//   - frameworks_count     int/string
//   - total_controls       int/string
//   - overdue_remediations int/string
//   - framework_scores     []interface{} of maps
//   - gaps                 []interface{} of maps
func (g *ReportPDFGenerator) GenerateComplianceReport(data interface{}) ([]byte, error) {
	reportData, _ := data.(map[string]interface{})

	pdf := g.newDoc("Compliance Status Report")

	// Cover page
	g.addCoverPage(pdf, "Compliance Status Report", "Framework Compliance Assessment & Gap Analysis")

	// Table of contents
	g.addTableOfContents(pdf, []string{
		"Executive Summary",
		"Framework Compliance Scores",
		"Gap Analysis",
		"Appendix: Methodology",
	})

	// Executive Summary
	pdf.AddPage()
	g.addSectionTitle(pdf, "1. Executive Summary")

	overallScore := "\u2014"
	scoreColor := "amber"
	if s, ok := reportData["overall_score"].(float64); ok {
		overallScore = fmt.Sprintf("%.1f%%", s)
		if s >= 80 {
			scoreColor = "green"
		} else if s < 60 {
			scoreColor = "red"
		}
	}

	g.addKPIRow(pdf, []struct{ Label, Value, Color string }{
		{"Overall Compliance Score", overallScore, scoreColor},
		{"Frameworks Adopted", fmt.Sprintf("%v", reportData["frameworks_count"]), ""},
		{"Total Controls", fmt.Sprintf("%v", reportData["total_controls"]), ""},
		{"Overdue Remediations", fmt.Sprintf("%v", reportData["overdue_remediations"]), "red"},
	})

	g.addParagraph(pdf, "This report presents the current compliance status across all adopted "+
		"frameworks, including control implementation rates, maturity levels, and "+
		"identified gaps requiring remediation.")

	// Framework Scores
	g.addSectionTitle(pdf, "2. Framework Compliance Scores")

	if scores, ok := reportData["framework_scores"].([]interface{}); ok {
		headers := []string{"Framework", "Version", "Score", "Implemented", "Partial", "Gaps", "Maturity"}
		widths := []float64{45, 20, 20, 25, 25, 25, 30}
		var rows [][]string
		for _, s := range scores {
			if score, ok := s.(map[string]interface{}); ok {
				rows = append(rows, []string{
					fmt.Sprintf("%v", score["framework_name"]),
					fmt.Sprintf("%v", score["framework_version"]),
					fmt.Sprintf("%.1f%%", score["compliance_score"]),
					fmt.Sprintf("%v", score["implemented_count"]),
					fmt.Sprintf("%v", score["partial_count"]),
					fmt.Sprintf("%v", score["not_implemented_count"]),
					fmt.Sprintf("%.1f", score["avg_maturity_level"]),
				})
			}
		}
		g.addTable(pdf, headers, widths, rows)
	}

	// Gap Analysis
	g.addSectionTitle(pdf, "3. Gap Analysis")
	g.addParagraph(pdf, "The following controls are not yet fully implemented and require "+
		"attention. Controls are sorted by risk impact (critical first).")

	if gaps, ok := reportData["gaps"].([]interface{}); ok && len(gaps) > 0 {
		headers := []string{"Control", "Framework", "Status", "Risk", "Owner", "Due Date"}
		widths := []float64{25, 35, 30, 25, 40, 35}
		var rows [][]string
		limit := len(gaps)
		if limit > 30 {
			limit = 30
		}
		for _, gi := range gaps[:limit] {
			if gap, ok := gi.(map[string]interface{}); ok {
				rows = append(rows, []string{
					fmt.Sprintf("%v", gap["control_code"]),
					fmt.Sprintf("%v", gap["framework_name"]),
					fmt.Sprintf("%v", gap["status"]),
					fmt.Sprintf("%v", gap["risk_if_not_implemented"]),
					fmt.Sprintf("%v", gap["owner_name"]),
					fmt.Sprintf("%v", gap["remediation_due_date"]),
				})
			}
		}
		g.addTable(pdf, headers, widths, rows)
	}

	// Appendix
	pdf.AddPage()
	g.addSectionTitle(pdf, "Appendix: Methodology")
	g.addParagraph(pdf, "Compliance scores are calculated using a weighted formula: "+
		"Effective=1.0, Implemented=0.85, Partial=0.50, Planned=0.15, "+
		"Not Implemented=0.00. Controls marked as Not Applicable are excluded "+
		"from the denominator.")
	g.addParagraph(pdf, "Maturity levels follow the CMMI model: 0=Non-existent, "+
		"1=Initial, 2=Managed, 3=Defined, 4=Quantitatively Managed, 5=Optimizing.")

	return g.render(pdf)
}

// GenerateRiskReport builds a risk register PDF.
//
// Expected data keys (map[string]interface{}):
//   - total_risks               int/string
//   - critical_count            int/string
//   - avg_residual_score        float64
//   - treatment_completion_rate float64
//   - top_risks                 []interface{} of maps
//   - treatment_summary         map[string]interface{}
func (g *ReportPDFGenerator) GenerateRiskReport(data interface{}) ([]byte, error) {
	reportData, _ := data.(map[string]interface{})

	pdf := g.newDoc("Risk Register Report")
	g.addCoverPage(pdf, "Risk Register Report", "Enterprise Risk Assessment & Treatment Status")

	// Table of contents
	g.addTableOfContents(pdf, []string{
		"Risk Summary",
		"Top Risks by Residual Score",
		"Treatment Progress",
	})

	pdf.AddPage()
	g.addSectionTitle(pdf, "1. Risk Summary")

	totalRisks := fmt.Sprintf("%v", reportData["total_risks"])
	criticalCount := fmt.Sprintf("%v", reportData["critical_count"])
	avgScore := "\u2014"
	if s, ok := reportData["avg_residual_score"].(float64); ok {
		avgScore = fmt.Sprintf("%.1f", s)
	}
	treatmentRate := "\u2014"
	if s, ok := reportData["treatment_completion_rate"].(float64); ok {
		treatmentRate = fmt.Sprintf("%.0f%%", s)
	}

	g.addKPIRow(pdf, []struct{ Label, Value, Color string }{
		{"Total Active Risks", totalRisks, ""},
		{"Critical Risks", criticalCount, "red"},
		{"Avg Residual Score", avgScore, "amber"},
		{"Treatment Completion", treatmentRate, "green"},
	})

	// Top Risks
	g.addSectionTitle(pdf, "2. Top Risks by Residual Score")
	if risks, ok := reportData["top_risks"].([]interface{}); ok && len(risks) > 0 {
		headers := []string{"Ref", "Title", "Category", "Inherent", "Residual", "Level", "Owner"}
		widths := []float64{20, 50, 30, 20, 20, 20, 30}
		var rows [][]string
		for _, r := range risks {
			if risk, ok := r.(map[string]interface{}); ok {
				rows = append(rows, []string{
					fmt.Sprintf("%v", risk["risk_ref"]),
					fmt.Sprintf("%v", risk["title"]),
					fmt.Sprintf("%v", risk["category_name"]),
					fmt.Sprintf("%v", risk["inherent_risk_score"]),
					fmt.Sprintf("%v", risk["residual_risk_score"]),
					fmt.Sprintf("%v", risk["residual_risk_level"]),
					fmt.Sprintf("%v", risk["owner_name"]),
				})
			}
		}
		g.addTable(pdf, headers, widths, rows)
	}

	// Treatment Progress
	g.addSectionTitle(pdf, "3. Treatment Progress")
	g.addParagraph(pdf, "Summary of risk treatment plans and their current status.")

	if treatments, ok := reportData["treatment_summary"].(map[string]interface{}); ok {
		headers := []string{"Status", "Count"}
		widths := []float64{100, 90}
		rows := [][]string{
			{"Planned", fmt.Sprintf("%v", treatments["planned"])},
			{"In Progress", fmt.Sprintf("%v", treatments["in_progress"])},
			{"Completed", fmt.Sprintf("%v", treatments["completed"])},
			{"Overdue", fmt.Sprintf("%v", treatments["overdue"])},
		}
		g.addTable(pdf, headers, widths, rows)
	}

	return g.render(pdf)
}

// GenerateAuditReport builds an audit findings PDF.
//
// Expected data keys (map[string]interface{}):
//   - total_findings    int/string
//   - critical_findings int/string
//   - high_findings     int/string
//   - open_findings     int/string
//   - findings          []interface{} of maps
func (g *ReportPDFGenerator) GenerateAuditReport(data interface{}) ([]byte, error) {
	reportData, _ := data.(map[string]interface{})

	pdf := g.newDoc("Audit Findings Report")
	g.addCoverPage(pdf, "Audit Findings Report", "Internal Audit Assessment Results")

	// Table of contents
	g.addTableOfContents(pdf, []string{
		"Audit Summary",
		"Findings Detail",
	})

	pdf.AddPage()
	g.addSectionTitle(pdf, "1. Audit Summary")

	g.addKPIRow(pdf, []struct{ Label, Value, Color string }{
		{"Total Findings", fmt.Sprintf("%v", reportData["total_findings"]), ""},
		{"Critical", fmt.Sprintf("%v", reportData["critical_findings"]), "red"},
		{"High", fmt.Sprintf("%v", reportData["high_findings"]), "amber"},
		{"Open", fmt.Sprintf("%v", reportData["open_findings"]), "red"},
	})

	g.addSectionTitle(pdf, "2. Findings Detail")
	if findings, ok := reportData["findings"].([]interface{}); ok && len(findings) > 0 {
		headers := []string{"Ref", "Title", "Severity", "Status", "Due Date", "Responsible"}
		widths := []float64{22, 50, 22, 22, 30, 44}
		var rows [][]string
		for _, f := range findings {
			if finding, ok := f.(map[string]interface{}); ok {
				rows = append(rows, []string{
					fmt.Sprintf("%v", finding["finding_ref"]),
					fmt.Sprintf("%v", finding["title"]),
					fmt.Sprintf("%v", finding["severity"]),
					fmt.Sprintf("%v", finding["status"]),
					fmt.Sprintf("%v", finding["due_date"]),
					fmt.Sprintf("%v", finding["responsible_name"]),
				})
			}
		}
		g.addTable(pdf, headers, widths, rows)
	}

	return g.render(pdf)
}
