package service

import (
	"archive/zip"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"time"

	"github.com/google/uuid"

	"github.com/complianceforge/platform/internal/config"
	"github.com/complianceforge/platform/internal/models"
)

const (
	MaximumSupportBundleBytes = models.MaximumSupportBundleBytes
	supportRedactionProfile   = models.SupportBundleRedactionProfile
)

var (
	ErrInvalidSupportBundleRequest = errors.New("explicit health-and-posture consent is required")
	ErrSupportBundleUnavailable    = errors.New("support bundle is unavailable")
	supportVersionPattern          = regexp.MustCompile(`^v?([0-9]{1,6}\.[0-9]{1,6}\.[0-9]{1,6})(?:-[A-Za-z0-9.-]{1,40})?(?:\+[A-Za-z0-9.-]{1,40})?$`)
)

type SupportBundleSnapshotProvider interface {
	GetSnapshot(context.Context, string) (*models.DiagnosticsSnapshot, error)
}

type SupportBundleAuditStore interface {
	RecordSupportBundleGeneration(context.Context, models.SupportBundleAudit) error
}

type SupportBundleService struct {
	snapshots     SupportBundleSnapshotProvider
	audit         SupportBundleAuditStore
	configuration models.SupportBundleConfiguration
	now           func() time.Time
}

func NewSupportBundleService(
	snapshots SupportBundleSnapshotProvider, audit SupportBundleAuditStore, cfg *config.Config,
) (*SupportBundleService, error) {
	if interfaceValueIsNil(snapshots) || interfaceValueIsNil(audit) || cfg == nil {
		return nil, errors.New("support bundle requires snapshots, durable consent audit, and configuration")
	}
	return &SupportBundleService{snapshots: snapshots, audit: audit, configuration: supportConfiguration(*cfg), now: time.Now}, nil
}

// Generate never sends data to a support provider and never stores the ZIP.
// Durable consent evidence is a prerequisite to releasing the generated bytes.
func (s *SupportBundleService) Generate(
	ctx context.Context, organizationID, actorID, requestID string, req models.SupportBundleRequest,
) (*models.SupportBundleArtifact, error) {
	if !req.Consent || req.Scope != models.SupportBundleScope || !supportUUID(organizationID) || !supportUUID(actorID) {
		return nil, ErrInvalidSupportBundleRequest
	}
	if requestID != "" && !supportUUID(requestID) {
		return nil, ErrInvalidSupportBundleRequest
	}
	if err := ctx.Err(); err != nil {
		return nil, ErrSupportBundleUnavailable
	}
	snapshot, err := s.snapshots.GetSnapshot(ctx, organizationID)
	if err != nil || snapshot == nil || snapshot.OrganizationID != organizationID {
		return nil, ErrSupportBundleUnavailable
	}
	generatedAt := s.now().UTC()
	configBytes, err := supportJSON(s.configuration)
	if err != nil {
		return nil, ErrSupportBundleUnavailable
	}
	fingerprint := supportSHA256(configBytes)
	healthBytes, err := supportJSON(supportHealth(snapshot))
	if err != nil {
		return nil, ErrSupportBundleUnavailable
	}
	bundleID := uuid.NewString()
	files := []supportFile{
		{name: "configuration.json", data: configBytes},
		{name: "health.json", data: healthBytes},
		{name: "README.txt", data: []byte(models.SupportBundleReadme)},
	}
	manifest := models.SupportBundleManifest{
		SchemaVersion: 1, BundleID: bundleID, OrganizationID: organizationID,
		GeneratedAt: generatedAt, ConsentRecordedAt: generatedAt,
		Scope: req.Scope, RedactionProfile: supportRedactionProfile,
		ConfigurationFingerprint: fingerprint,
		Files:                    make([]models.SupportBundleFile, 0, len(files)),
		Excluded:                 models.SupportBundleExclusions(),
	}
	for _, file := range files {
		manifest.Files = append(manifest.Files, models.SupportBundleFile{
			Name: file.name, Bytes: len(file.data), SHA256: supportSHA256(file.data),
		})
	}
	manifestBytes, err := supportJSON(manifest)
	if err != nil {
		return nil, ErrSupportBundleUnavailable
	}
	files = append(files, supportFile{name: "manifest.json", data: manifestBytes})
	archive, err := buildSupportArchive(files)
	if err != nil || ctx.Err() != nil {
		return nil, ErrSupportBundleUnavailable
	}
	archiveHash := supportSHA256(archive)
	if err := s.audit.RecordSupportBundleGeneration(ctx, models.SupportBundleAudit{
		BundleID: bundleID, OrganizationID: organizationID, ActorID: actorID,
		RequestID: requestID, GeneratedAt: generatedAt, Scope: req.Scope,
		RedactionProfile: supportRedactionProfile, ConfigurationFingerprint: fingerprint,
		ArchiveSHA256: archiveHash, ArchiveBytes: len(archive),
	}); err != nil {
		return nil, ErrSupportBundleUnavailable
	}
	return &models.SupportBundleArtifact{ID: bundleID, SHA256: archiveHash, Bytes: archive}, nil
}

func supportUUID(value string) bool {
	id, err := uuid.Parse(value)
	return err == nil && id != uuid.Nil && id.String() == value
}

func supportJSON(value any) ([]byte, error) {
	encoded, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}

func supportSHA256(value []byte) string {
	sum := sha256.Sum256(value)
	return hex.EncodeToString(sum[:])
}

func supportStatus(value models.DiagnosticStatus) models.DiagnosticStatus {
	switch value {
	case models.DiagnosticStatusHealthy, models.DiagnosticStatusWarning, models.DiagnosticStatusCritical, models.DiagnosticStatusUnknown:
		return value
	default:
		return models.DiagnosticStatusUnknown
	}
}

func supportHealth(snapshot *models.DiagnosticsSnapshot) models.SupportBundleHealth {
	health := models.SupportBundleHealth{
		OrganizationID: snapshot.OrganizationID, GeneratedAt: snapshot.GeneratedAt,
		OverallStatus: supportStatus(snapshot.OverallStatus),
		Dependencies:  []models.SupportDependency{}, Migration: snapshot.Migration,
		Queue: snapshot.Queue, Notifications: snapshot.Notifications, Connectors: snapshot.Connectors,
	}
	health.Migration.Status = supportStatus(health.Migration.Status)
	health.Queue.Status = supportStatus(health.Queue.Status)
	health.Notifications.Status = supportStatus(health.Notifications.Status)
	health.Connectors.Status = supportStatus(health.Connectors.Status)
	seen := make(map[string]bool)
	for _, dependency := range snapshot.Dependencies {
		switch dependency.Key {
		case "postgres", "redis", "rabbitmq", "evidence_scanner", "object_storage", "ai_provider":
		default:
			continue
		}
		if seen[dependency.Key] {
			continue
		}
		seen[dependency.Key] = true
		health.Dependencies = append(health.Dependencies, models.SupportDependency{
			Key: dependency.Key, Status: supportStatus(dependency.Status), Critical: dependency.Critical,
			LatencyMS: supportBudget(dependency.LatencyMS, 60_000),
		})
	}
	sort.Slice(health.Dependencies, func(i, j int) bool { return health.Dependencies[i].Key < health.Dependencies[j].Key })
	return health
}

func supportBudget(value, maximum int64) int64 {
	if value < 0 || value > maximum {
		return 0 // Zero is documented as unspecified/invalid, not a raw config value.
	}
	return value
}

func supportConfiguration(cfg config.Config) models.SupportBundleConfiguration {
	environment := "unknown"
	switch cfg.App.Env {
	case "production", "staging", "development", "test":
		environment = cfg.App.Env
	}
	version := "unknown"
	if match := supportVersionPattern.FindStringSubmatch(cfg.Observability.ServiceVersion); len(match) == 2 {
		version = match[1] // Never expose internal prerelease/build labels.
	}
	value := models.SupportBundleConfiguration{
		SchemaVersion: 1, Environment: environment, ServiceVersion: version,
		MetricsEnabled: cfg.Observability.MetricsEnabled, TracingEnabled: cfg.Observability.TracingEnabled,
		DatabaseMaximumConns:   supportBudget(int64(cfg.Database.MaxConns), 100_000),
		DatabaseMinimumConns:   supportBudget(int64(cfg.Database.MinConns), 100_000),
		MaximumEvidenceBytes:   supportBudget(cfg.Evidence.MaximumUploadBytes, 1<<40),
		ScannerTimeoutSeconds:  supportBudget(int64(cfg.Evidence.ScannerTimeoutSeconds), 300),
		RequestReadSeconds:     supportBudget(int64(cfg.HTTP.ReadTimeoutSeconds), 3600),
		RequestWriteSeconds:    supportBudget(int64(cfg.HTTP.WriteTimeoutSeconds), 3600),
		ShutdownTimeoutSeconds: supportBudget(int64(cfg.HTTP.ShutdownTimeoutSeconds), 300),
		Posture:                []models.SupportPosture{},
	}
	for _, check := range configurationDiagnostics(cfg) {
		value.Posture = append(value.Posture, models.SupportPosture{Key: check.Key, Status: supportStatus(check.Status)})
	}
	return value
}

type supportFile struct {
	name string
	data []byte
}

func buildSupportArchive(files []supportFile) ([]byte, error) {
	var buffer bytes.Buffer
	writer := zip.NewWriter(&buffer)
	total := 0
	for _, file := range files {
		total += len(file.data)
		if total > MaximumSupportBundleBytes {
			return nil, errors.New("support bundle size exceeds its reviewed budget")
		}
		// Store (no compression), fixed filenames, and a fixed ZIP timestamp keep
		// this artifact bounded and avoid decompression expansion or path input.
		entry, err := writer.CreateHeader(&zip.FileHeader{Name: file.name, Method: zip.Store, Modified: time.Date(1980, 1, 1, 0, 0, 0, 0, time.UTC)})
		if err != nil {
			return nil, fmt.Errorf("create support member: %w", err)
		}
		if _, err := entry.Write(file.data); err != nil {
			return nil, fmt.Errorf("write support member: %w", err)
		}
	}
	if err := writer.Close(); err != nil {
		return nil, fmt.Errorf("close support archive: %w", err)
	}
	if buffer.Len() > MaximumSupportBundleBytes {
		return nil, errors.New("support archive exceeds its reviewed budget")
	}
	return buffer.Bytes(), nil
}
